shop_account:
    path:     /account
    defaults: { _controller: FrontBundle:Home:shopAccount }

index:
    path:     /index
    defaults: { _controller: FrontBundle:Home:index }


shop_product:
    path:     /product
    defaults: { _controller: FrontBundle:Home:shopProduct }

shop_cart:
    path:     /cart
    defaults: { _controller: FrontBundle:Home:shopCart }

pricing:
    path:   /pricing
    defaults: { _controller: FrontBundle:Home:pricing }
