<?php

namespace BackendBundle\Repository;

/**
 * PricingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PricingRepository extends \Doctrine\ORM\EntityRepository
{

    public function getPricingByType($type)
    {
        var_dump($type);
        $dql = "SELECT p FROM BackendBundle\Entity\Pricing p WHERE p.forEnterprise = '". $type . "'";

        return $this->getEntityManager()->createQuery(
            $dql)->execute();
    }
}
