<?php

namespace BackendBundle\Repository;

/**
 * PricingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PricingRepository extends \Doctrine\ORM\EntityRepository
{

    public function getPricingByType($type)
    {
        $dql = "SELECT p FROM BackendBundle\Entity\Pricing p WHERE p.forEnterprise = '". $type . "'";
        $packages = $this->getEntityManager()->createQuery($dql)->getResult();
        return $packages;
    }
}
