<?php

namespace BackendBundle\Repository;

/**
 * SubCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubCategoryRepository extends \Doctrine\ORM\EntityRepository
{

    public function findCorrespondingSubCategories($category)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT sub_category FROM BackendBundle\Entity\SubCategory sub_category WHERE sub_category.category.id = ' . $category
            )
            ->getResult();
    }


}
