font_shop:
    path:     /shop
    defaults: { _controller: FrontendBundle:Home:shop }

homepage:
    path:     /
    defaults: { _controller: FrontendBundle:Home:index }


front_product:
    path:     /product
    defaults: { _controller: FrontendBundle:Home:product }

front_cart:
    path:     /cart
    defaults: { _controller: FrontendBundle:Home:cart }

front_checkout:
    path:     /checkout
    defaults: { _controller: FrontendBundle:Home:checkout }
front_contact:
    path:     /contact
    defaults: { _controller: FrontendBundle:Home:contact }
#
#pricing:
#    path:   /pricing
#    defaults: { _controller: FrontendBundle:Home:pricing }