font_shop:
    path:     /shop
    defaults: { _controller: FrontendBundle:Home:shop }

homepage:
    path:     /
    defaults: { _controller: FrontendBundle:Home:index }

front_wishlist:
    path:     /wishlist
    defaults: { _controller: FrontendBundle:Home:wishlist }
front_wishlist_add:
    path:     /wishlist_add/{id}
    defaults: { _controller: FrontendBundle:Home:wishlistAdd }

front_remove_product_wishlist:
    path:     /remove_product_wishlist/{id}
    defaults: { _controller: FrontendBundle:Home:wishlistRemove }
front_account:
    path:     /account
    defaults: { _controller: FrontendBundle:Home:account }

front_post_product:
    path:     /post
    defaults: { _controller: FrontendBundle:Home:postProduct }

front_product:
    path:     /product/{id}
    defaults: { _controller: FrontendBundle:Home:product }

front_my_products:
    path:     /my_products
    defaults: { _controller: FrontendBundle:Home:myProduct }

front_products_by_shop:
    path:     /products_by_shop/{id}
    defaults: { _controller: FrontendBundle:Home:productsByShop }

front_delete_product:
    path:     /delete_product/{id}
    defaults: { _controller: FrontendBundle:Home:deleteProduct }

front_edit_product:
    path:     /edit_product/{id}
    defaults: { _controller: FrontendBundle:Home:editProduct }

delete_image:
    path:     /delete_image/{id}
    defaults: { _controller: FrontendBundle:Home:deleteImage }

front_contact:
    path:     /contact
    defaults: { _controller: FrontendBundle:Home:contact }

front_checkout:
    path:     /checkout
    defaults: { _controller: FrontendBundle:Home:checkout }

account_pricing:
    path:     /pricing/{account_type}
    defaults: { _controller: FrontendBundle:Home:pricing }

account_type:
    path:   /type
    defaults: { _controller: FrontendBundle:Home:type }


add_image:
    path:   /add_image/{id}
    defaults: { _controller: FrontendBundle:Home:type }

get_sub_categories:
    path:     /get_sub_categories
    defaults: { _controller: FrontendBundle:Home:getSubCategories }

get_by_category:
    path:     /get_by_category/{id}
    defaults: { _controller: FrontendBundle:Home:getByCategory }
get_by_sub_category:
    path:     /get_by_sub_category/{id}
    defaults: { _controller: FrontendBundle:Home:getBySubCategory }