<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZzvd4yj\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZzvd4yj/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerZzvd4yj.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerZzvd4yj\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerZzvd4yj\appDevDebugProjectContainer([
    'container.build_hash' => 'Zzvd4yj',
    'container.build_id' => '64ca3da7',
    'container.build_time' => 1563962446,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZzvd4yj');
