<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGszbrw7\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGszbrw7/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerGszbrw7.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerGszbrw7\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerGszbrw7\appDevDebugProjectContainer([
    'container.build_hash' => 'Gszbrw7',
    'container.build_id' => 'cfa3fd38',
    'container.build_time' => 1563799414,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGszbrw7');
