<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerH9qyjze\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerH9qyjze/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerH9qyjze.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerH9qyjze\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerH9qyjze\appDevDebugProjectContainer([
    'container.build_hash' => 'H9qyjze',
    'container.build_id' => 'a52e6b38',
    'container.build_time' => 1563538312,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerH9qyjze');
